add OSL license injection [#174128011]

diff --git a/tasks/add-osl/task b/tasks/add-osl/task
--- a/tasks/add-osl/task
+++ b/tasks/add-osl/task
@@ -17,3 +17,6 @@ echo "Versions Match, appending OSL"
 zip $TILE_FILENAME $OSL_FILENAME > /dev/null
 
 echo "OSL appended"
+
+echo "Temporarily always fail"
+exit 1
